branches:
  except:
    - /^legacy\/.*$/
    - heroku
language: php
php:
  - 5.5
  - 5.6
  - hhvm
env:
  - DB=sqlite
  - DB=postgres
  - DB=mysql
sudo: false
before_install:
  - composer self-update
install: travis_retry composer install --no-interaction
before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS solder;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database solder;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS solder;'; fi"
  - php artisan migrate:refresh --force
  - php artisan db:seed --class="TestSeeder" --force
script: vendor/bin/phpunit --verbose
addons:
  hosts:
    - homestead
